name: ms-mswin-update-releases (Update)

on: [workflow_dispatch]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Run the PowerShell Script
        shell: pwsh
        run: ./scripts/ms/mswin/releases.ps1
      - name: Submit a Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Updated Microsoft Windows Releases JSON
          committer: GitHub <noreply@github.com>
          branch: au/ms-mswin-update-releases
          branch-suffix: timestamp
          delete-branch: true
          title: Automatic Update of Windows 10 Releases
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
          